### ISSUE TITLE
Validar campo de usuario.solo valores alfanumericos permitidos (backend/frontend)

### ISSUE THREAD

**Issue by YamilG** [YamilG/agendadigital#8]
Validar que el nombre de usuario no permita caracteres prohibidos (\* /? _ etc)

**Comment by justrdk** [comment]
solo valores alfanumericos son permitidos?

**Comment by YamilG** [comment]
Esa sería mi sugerencia. Supongo que es el estándar.

**Comment by justrdk** [comment]
Termine validando todos los campos del form, no solo el usuario.
@YamilG 
Pull request : https://github.com/YamilG/agendadigital/pull/15

**Comment by YamilG** [comment]
¡Excelente!
